
/*
 * This file was automatically generated by ml-idl
 * (Mon Aug 13 15:59:31 2007)
 */

#include "ml-base.h"
#include "ml-values.h"
#include "ml-objects.h"

#include "sml-basis.h"

ML_Value ml_stub_getRoundingMode (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  int ml_opresult;
  ml_opresult = getRoundingMode ();
  ml_argresult = ML_Int(ml_opresult);
  return ml_argresult;
}

ML_Value ml_stub_setRoundingMode (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_mode;
  int ml_op_mode;
  ml_arg_mode = v;
  ml_op_mode = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_mode))).Val();
  setRoundingMode (ml_op_mode);
  return ML_UNIT;
}

ML_Value ml_stub_openFile (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_s;
  ML_Value ml_arg_flags;
  ML_iodesc_t ml_opresult;
  ML_string_t ml_op_s;
  int ml_op_flags;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_s = ml_arg_tuple.Get(ctx, 1);
  ml_arg_flags = ml_arg_tuple.Get(ctx, 2);
  ml_op_s = ml_arg_s;
  ml_op_flags = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_flags))).Val();
  ml_opresult = openFile (ctx,ml_op_s, ml_op_flags);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_closeFile (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_iod;
  ML_iodesc_t ml_op_iod;
  ml_arg_iod = v;
  ml_op_iod = ml_arg_iod;
  closeFile (ml_op_iod);
  return ML_UNIT;
}

ML_Value ml_stub_cmpIODesc (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_iod1;
  ML_Value ml_arg_iod2;
  int ml_opresult;
  ML_iodesc_t ml_op_iod1;
  ML_iodesc_t ml_op_iod2;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_iod1 = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod2 = ml_arg_tuple.Get(ctx, 2);
  ml_op_iod1 = ml_arg_iod1;
  ml_op_iod2 = ml_arg_iod2;
  ml_opresult = cmpIODesc (ml_op_iod1, ml_op_iod2);
  ml_argresult = ML_Int(ml_opresult);
  return ml_argresult;
}

ML_Value ml_stub_readTextVec (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_nbytes;
  ML_charvec_opt_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  int ml_op_nbytes;
  ML_Tuple<3>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<3>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 3);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_opresult = readTextVec (ctx,ml_op_noblock, ml_op_iod, ml_op_nbytes);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_readTextArr (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_arr;
  ML_Value ml_arg_nbytes;
  ML_Value ml_arg_offset;
  ML_int_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  ML_chararr_t ml_op_arr;
  int ml_op_nbytes;
  int ml_op_offset;
  ML_Tuple<5>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<5>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_arr = ml_arg_tuple.Get(ctx, 3);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 4);
  ml_arg_offset = ml_arg_tuple.Get(ctx, 5);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_arr = ml_arg_arr;
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_op_offset = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_offset))).Val();
  ml_opresult = readTextArr (ctx,ml_op_noblock, ml_op_iod, ml_op_arr, ml_op_nbytes, ml_op_offset);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_writeTextVec (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_buf;
  ML_Value ml_arg_offset;
  ML_Value ml_arg_nbytes;
  ML_int_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  ML_charvec_t ml_op_buf;
  int ml_op_offset;
  int ml_op_nbytes;
  ML_Tuple<5>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<5>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_buf = ml_arg_tuple.Get(ctx, 3);
  ml_arg_offset = ml_arg_tuple.Get(ctx, 4);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 5);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_buf = ml_arg_buf;
  ml_op_offset = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_offset))).Val();
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_opresult = writeTextVec (ctx,ml_op_noblock, ml_op_iod, ml_op_buf, ml_op_offset, ml_op_nbytes);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_writeTextArr (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_buf;
  ML_Value ml_arg_offset;
  ML_Value ml_arg_nbytes;
  ML_int_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  ML_chararr_t ml_op_buf;
  int ml_op_offset;
  int ml_op_nbytes;
  ML_Tuple<5>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<5>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_buf = ml_arg_tuple.Get(ctx, 3);
  ml_arg_offset = ml_arg_tuple.Get(ctx, 4);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 5);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_buf = ml_arg_buf;
  ml_op_offset = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_offset))).Val();
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_opresult = writeTextArr (ctx,ml_op_noblock, ml_op_iod, ml_op_buf, ml_op_offset, ml_op_nbytes);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_readBinVec (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_nbytes;
  ML_word8vec_opt_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  int ml_op_nbytes;
  ML_Tuple<3>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<3>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 3);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_opresult = readBinVec (ctx,ml_op_noblock, ml_op_iod, ml_op_nbytes);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_readBinArr (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_arr;
  ML_Value ml_arg_nbytes;
  ML_Value ml_arg_offset;
  ML_int_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  ML_word8arr_t ml_op_arr;
  int ml_op_nbytes;
  int ml_op_offset;
  ML_Tuple<5>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<5>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_arr = ml_arg_tuple.Get(ctx, 3);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 4);
  ml_arg_offset = ml_arg_tuple.Get(ctx, 5);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_arr = ml_arg_arr;
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_op_offset = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_offset))).Val();
  ml_opresult = readBinArr (ctx,ml_op_noblock, ml_op_iod, ml_op_arr, ml_op_nbytes, ml_op_offset);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_writeBinVec (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_buf;
  ML_Value ml_arg_offset;
  ML_Value ml_arg_nbytes;
  ML_int_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  ML_word8vec_t ml_op_buf;
  int ml_op_offset;
  int ml_op_nbytes;
  ML_Tuple<5>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<5>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_buf = ml_arg_tuple.Get(ctx, 3);
  ml_arg_offset = ml_arg_tuple.Get(ctx, 4);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 5);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_buf = ml_arg_buf;
  ml_op_offset = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_offset))).Val();
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_opresult = writeBinVec (ctx,ml_op_noblock, ml_op_iod, ml_op_buf, ml_op_offset, ml_op_nbytes);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_writeBinArr (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_noblock;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_buf;
  ML_Value ml_arg_offset;
  ML_Value ml_arg_nbytes;
  ML_int_t ml_opresult;
  ML_bool_t ml_op_noblock;
  ML_iodesc_t ml_op_iod;
  ML_word8arr_t ml_op_buf;
  int ml_op_offset;
  int ml_op_nbytes;
  ML_Tuple<5>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<5>) *> (&(v)));
  ml_arg_noblock = ml_arg_tuple.Get(ctx, 1);
  ml_arg_iod = ml_arg_tuple.Get(ctx, 2);
  ml_arg_buf = ml_arg_tuple.Get(ctx, 3);
  ml_arg_offset = ml_arg_tuple.Get(ctx, 4);
  ml_arg_nbytes = ml_arg_tuple.Get(ctx, 5);
  ml_op_noblock = ml_arg_noblock;
  ml_op_iod = ml_arg_iod;
  ml_op_buf = ml_arg_buf;
  ml_op_offset = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_offset))).Val();
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_opresult = writeBinArr (ctx,ml_op_noblock, ml_op_iod, ml_op_buf, ml_op_offset, ml_op_nbytes);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_getPos (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_iod;
  ML_int32_t ml_opresult;
  ML_iodesc_t ml_op_iod;
  ml_arg_iod = v;
  ml_op_iod = ml_arg_iod;
  ml_opresult = getPos (ctx,ml_op_iod);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_setPos (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_iod;
  ML_Value ml_arg_offset;
  ML_Value ml_arg_whence;
  ML_unit_t ml_opresult;
  ML_iodesc_t ml_op_iod;
  ML_int32_t ml_op_offset;
  int ml_op_whence;
  ML_Tuple<3>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<3>) *> (&(v)));
  ml_arg_iod = ml_arg_tuple.Get(ctx, 1);
  ml_arg_offset = ml_arg_tuple.Get(ctx, 2);
  ml_arg_whence = ml_arg_tuple.Get(ctx, 3);
  ml_op_iod = ml_arg_iod;
  ml_op_offset = ml_arg_offset;
  ml_op_whence = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_whence))).Val();
  ml_opresult = setPos (ctx,ml_op_iod, ml_op_offset, ml_op_whence);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_getStdIn (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_iodesc_t ml_opresult;
  ml_opresult = getStdIn ();
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_getStdOut (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_iodesc_t ml_opresult;
  ml_opresult = getStdOut ();
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_getStdErr (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_iodesc_t ml_opresult;
  ml_opresult = getStdErr ();
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_errorName (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_err;
  ML_string_t ml_opresult;
  Int32_t ml_op_err;
  ml_arg_err = v;
  ml_op_err = (*(reinterpret_cast<(ML_Int32) *> (&(ml_arg_err))).Val();
  ml_opresult = errorName (ctx,ml_op_err);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_errorMessage (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_err;
  ML_string_t ml_opresult;
  Int32_t ml_op_err;
  ml_arg_err = v;
  ml_op_err = (*(reinterpret_cast<(ML_Int32) *> (&(ml_arg_err))).Val();
  ml_opresult = errorMessage (ctx,ml_op_err);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_syserror (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_errName;
  ML_int_opt_t ml_opresult;
  char *ml_op_errName;
  ml_arg_errName = v;
  ml_op_errName = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_errName))).UnsafeCString();
  ml_opresult = syserror (ctx,ml_op_errName);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_osSystem (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_name;
  ML_int_t ml_opresult;
  char *ml_op_name;
  ml_arg_name = v;
  ml_op_name = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_name))).UnsafeCString();
  ml_opresult = osSystem (ctx,ml_op_name);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_exitProc (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_sts;
  int ml_op_sts;
  ml_arg_sts = v;
  ml_op_sts = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_sts))).Val();
  exitProc (ml_op_sts);
  return ML_UNIT;
}

ML_Value ml_stub_getEnv (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_ss;
  ML_string_opt_t ml_opresult;
  char *ml_op_ss;
  ml_arg_ss = v;
  ml_op_ss = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_ss))).UnsafeCString();
  ml_opresult = getEnv (ctx,ml_op_ss);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_osSleep (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_t;
  Time_t *ml_op_t;
  Time_t ml_tmp_0;
  ml_arg_t = v;
  (ml_tmp_0).seconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_arg_t))).Get(ctx, 1)))).Val();
  (ml_tmp_0).uSeconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_arg_t))).Get(ctx, 2)))).Val();
  ml_op_t = &ml_tmp_0;
  osSleep (ml_op_t);
  return ML_UNIT;
}

ML_Value ml_stub_openDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_directory_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = openDir (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_readDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_dir;
  ML_string_opt_t ml_opresult;
  ML_directory_t ml_op_dir;
  ml_arg_dir = v;
  ml_op_dir = ml_arg_dir;
  ml_opresult = readDir (ctx,ml_op_dir);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_rewindDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_dir;
  ML_unit_t ml_opresult;
  ML_directory_t ml_op_dir;
  ml_arg_dir = v;
  ml_op_dir = ml_arg_dir;
  ml_opresult = rewindDir (ctx,ml_op_dir);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_closeDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_dir;
  ML_unit_t ml_opresult;
  ML_directory_t ml_op_dir;
  ml_arg_dir = v;
  ml_op_dir = ml_arg_dir;
  ml_opresult = closeDir (ctx,ml_op_dir);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_chDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_unit_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = chDir (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_getDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_string_t ml_opresult;
  ml_opresult = getDir (ctx);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_mkDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_unit_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = mkDir (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_rmDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_unit_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = rmDir (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_isReg (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_bool_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = isReg (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_isDir (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_bool_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = isDir (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_isLink (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_bool_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = isLink (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_readLink (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_string_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = readLink (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_fileSize (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_int32_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = fileSize (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_modTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_int32_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = modTime (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_setTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_Value ml_arg_t;
  ML_unit_t ml_opresult;
  char *ml_op_path;
  Time_t *ml_op_t;
  Time_t ml_tmp_1;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_path = ml_arg_tuple.Get(ctx, 1);
  ml_arg_t = ml_arg_tuple.Get(ctx, 2);
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  if ((*(reinterpret_cast<(ML_Option<ML_Value>) *> (&(ml_arg_t))).isNONE()) {
    ml_op_t = NULL;
  } else {
    ML_Value ml_tmp_2;
    ml_tmp_2 = (*(reinterpret_cast<(ML_Option<ML_Value>) *> (&(ml_arg_t))).ValOf(ctx);
    (ml_tmp_1).seconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_tmp_2))).Get(ctx, 1)))).Val();
    (ml_tmp_1).uSeconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_tmp_2))).Get(ctx, 2)))).Val();
    ml_op_t = &ml_tmp_1;
  };
  ml_opresult = setTime (ctx,ml_op_path, ml_op_t);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_removeFile (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_unit_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = removeFile (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_renameFile (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_old;
  ML_Value ml_arg_new;
  ML_unit_t ml_opresult;
  char *ml_op_old;
  char *ml_op_new;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_old = ml_arg_tuple.Get(ctx, 1);
  ml_arg_new = ml_arg_tuple.Get(ctx, 2);
  ml_op_old = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_old))).UnsafeCString();
  ml_op_new = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_new))).UnsafeCString();
  ml_opresult = renameFile (ctx,ml_op_old, ml_op_new);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_fileAccess (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_Value ml_arg_mode;
  ML_bool_t ml_opresult;
  char *ml_op_path;
  int ml_op_mode;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_path = ml_arg_tuple.Get(ctx, 1);
  ml_arg_mode = ml_arg_tuple.Get(ctx, 2);
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_op_mode = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_mode))).Val();
  ml_opresult = fileAccess (ctx,ml_op_path, ml_op_mode);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_tmpName (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_string_t ml_opresult;
  ml_opresult = tmpName (ctx);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_fileId (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_path;
  ML_word8vec_t ml_opresult;
  char *ml_op_path;
  ml_arg_path = v;
  ml_op_path = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_path))).UnsafeCString();
  ml_opresult = fileId (ctx,ml_op_path);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_ioDescKind (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_iod;
  ML_int_t ml_opresult;
  ML_iodesc_t ml_op_iod;
  ml_arg_iod = v;
  ml_op_iod = ml_arg_iod;
  ml_opresult = ioDescKind (ctx,ml_op_iod);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_osPoll (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_pds;
  ML_Value ml_arg_t;
  ML_pollinfo_list_t ml_opresult;
  ML_polldesc_list_t ml_op_pds;
  Time_t *ml_op_t;
  Time_t ml_tmp_3;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_pds = ml_arg_tuple.Get(ctx, 1);
  ml_arg_t = ml_arg_tuple.Get(ctx, 2);
  ml_op_pds = ml_arg_pds;
  if ((*(reinterpret_cast<(ML_Option<ML_Value>) *> (&(ml_arg_t))).isNONE()) {
    ml_op_t = NULL;
  } else {
    ML_Value ml_tmp_4;
    ml_tmp_4 = (*(reinterpret_cast<(ML_Option<ML_Value>) *> (&(ml_arg_t))).ValOf(ctx);
    (ml_tmp_3).seconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_tmp_4))).Get(ctx, 1)))).Val();
    (ml_tmp_3).uSeconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_tmp_4))).Get(ctx, 2)))).Val();
    ml_op_t = &ml_tmp_3;
  };
  ml_opresult = osPoll (ctx,ml_op_pds, ml_op_t);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_now (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_t;
  Time_t *ml_op_t;
  Time_t out_ml_op_t;
  ML_Value ml_tmp_5_seconds;
  ML_Value ml_tmp_5_uSeconds;
  ml_op_t = &out_ml_op_t;
  now (ml_op_t);
  ml_tmp_5_secondsML_Int32(ctx,(*(ml_op_t)).seconds);
ml_tmp_5_uSecondsML_Int32(ctx,(*(ml_op_t)).uSeconds);
  {
    ML_Value vs[] = {ml_tmp_5_seconds, ml_tmp_5_uSeconds};
    ML_Tuple<2> r = ML_Tuple<2>(ctx, vs);
    ml_arg_t = r;
  };
  return ml_arg_t;
}

ML_Value ml_stub_ascTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_date;
  ML_string_t ml_opresult;
  Date_t *ml_op_date;
  Date_t ml_tmp_6;
  ml_arg_date = v;
  (ml_tmp_6).tm_sec = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 1)))).Val();
  (ml_tmp_6).tm_min = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 2)))).Val();
  (ml_tmp_6).tm_hour = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 3)))).Val();
  (ml_tmp_6).tm_mday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 4)))).Val();
  (ml_tmp_6).tm_mon = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 5)))).Val();
  (ml_tmp_6).tm_year = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 6)))).Val();
  (ml_tmp_6).tm_wday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 7)))).Val();
  (ml_tmp_6).tm_yday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 8)))).Val();
  (ml_tmp_6).tm_isdst = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 9)))).Val();
  ml_op_date = &ml_tmp_6;
  ml_opresult = ascTime (ctx,ml_op_date);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_strfTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_s;
  ML_Value ml_arg_date;
  ML_string_t ml_opresult;
  char *ml_op_s;
  Date_t *ml_op_date;
  Date_t ml_tmp_7;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_s = ml_arg_tuple.Get(ctx, 1);
  ml_arg_date = ml_arg_tuple.Get(ctx, 2);
  ml_op_s = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_s))).UnsafeCString();
  (ml_tmp_7).tm_sec = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 1)))).Val();
  (ml_tmp_7).tm_min = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 2)))).Val();
  (ml_tmp_7).tm_hour = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 3)))).Val();
  (ml_tmp_7).tm_mday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 4)))).Val();
  (ml_tmp_7).tm_mon = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 5)))).Val();
  (ml_tmp_7).tm_year = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 6)))).Val();
  (ml_tmp_7).tm_wday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 7)))).Val();
  (ml_tmp_7).tm_yday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 8)))).Val();
  (ml_tmp_7).tm_isdst = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 9)))).Val();
  ml_op_date = &ml_tmp_7;
  ml_opresult = strfTime (ctx,ml_op_s, ml_op_date);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_gmTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_t;
  ML_Value ml_arg_date;
  Time_t *ml_op_t;
  Date_t *ml_op_date;
  Date_t out_ml_op_date;
  Time_t ml_tmp_8;
  ML_Value ml_tmp_9_tm_sec;
  ML_Value ml_tmp_9_tm_min;
  ML_Value ml_tmp_9_tm_hour;
  ML_Value ml_tmp_9_tm_mday;
  ML_Value ml_tmp_9_tm_mon;
  ML_Value ml_tmp_9_tm_year;
  ML_Value ml_tmp_9_tm_wday;
  ML_Value ml_tmp_9_tm_yday;
  ML_Value ml_tmp_9_tm_isdst;
  ml_op_date = &out_ml_op_date;
  ml_arg_t = v;
  (ml_tmp_8).seconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_arg_t))).Get(ctx, 1)))).Val();
  (ml_tmp_8).uSeconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_arg_t))).Get(ctx, 2)))).Val();
  ml_op_t = &ml_tmp_8;
  gmTime (ml_op_t, ml_op_date);
  ml_tmp_9_tm_sec = ML_Int((*(ml_op_date)).tm_sec);
ml_tmp_9_tm_min = ML_Int((*(ml_op_date)).tm_min);
ml_tmp_9_tm_hour = ML_Int((*(ml_op_date)).tm_hour);
ml_tmp_9_tm_mday = ML_Int((*(ml_op_date)).tm_mday);
ml_tmp_9_tm_mon = ML_Int((*(ml_op_date)).tm_mon);
ml_tmp_9_tm_year = ML_Int((*(ml_op_date)).tm_year);
ml_tmp_9_tm_wday = ML_Int((*(ml_op_date)).tm_wday);
ml_tmp_9_tm_yday = ML_Int((*(ml_op_date)).tm_yday);
ml_tmp_9_tm_isdst = ML_Int((*(ml_op_date)).tm_isdst);
  {
    ML_Value vs[] = {ml_tmp_9_tm_sec, ml_tmp_9_tm_min, ml_tmp_9_tm_hour, ml_tmp_9_tm_mday, ml_tmp_9_tm_mon, ml_tmp_9_tm_year, ml_tmp_9_tm_wday, ml_tmp_9_tm_yday, ml_tmp_9_tm_isdst};
    ML_Tuple<9> r = ML_Tuple<9>(ctx, vs);
    ml_arg_date = r;
  };
  return ml_arg_date;
}

ML_Value ml_stub_localTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_t;
  ML_Value ml_arg_date;
  Time_t *ml_op_t;
  Date_t *ml_op_date;
  Date_t out_ml_op_date;
  Time_t ml_tmp_10;
  ML_Value ml_tmp_11_tm_sec;
  ML_Value ml_tmp_11_tm_min;
  ML_Value ml_tmp_11_tm_hour;
  ML_Value ml_tmp_11_tm_mday;
  ML_Value ml_tmp_11_tm_mon;
  ML_Value ml_tmp_11_tm_year;
  ML_Value ml_tmp_11_tm_wday;
  ML_Value ml_tmp_11_tm_yday;
  ML_Value ml_tmp_11_tm_isdst;
  ml_op_date = &out_ml_op_date;
  ml_arg_t = v;
  (ml_tmp_10).seconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_arg_t))).Get(ctx, 1)))).Val();
  (ml_tmp_10).uSeconds = (*(reinterpret_cast<(ML_Int32) *> (&((*(reinterpret_cast<(ML_Tuple<2>) *> (&(ml_arg_t))).Get(ctx, 2)))).Val();
  ml_op_t = &ml_tmp_10;
  localTime (ml_op_t, ml_op_date);
  ml_tmp_11_tm_sec = ML_Int((*(ml_op_date)).tm_sec);
ml_tmp_11_tm_min = ML_Int((*(ml_op_date)).tm_min);
ml_tmp_11_tm_hour = ML_Int((*(ml_op_date)).tm_hour);
ml_tmp_11_tm_mday = ML_Int((*(ml_op_date)).tm_mday);
ml_tmp_11_tm_mon = ML_Int((*(ml_op_date)).tm_mon);
ml_tmp_11_tm_year = ML_Int((*(ml_op_date)).tm_year);
ml_tmp_11_tm_wday = ML_Int((*(ml_op_date)).tm_wday);
ml_tmp_11_tm_yday = ML_Int((*(ml_op_date)).tm_yday);
ml_tmp_11_tm_isdst = ML_Int((*(ml_op_date)).tm_isdst);
  {
    ML_Value vs[] = {ml_tmp_11_tm_sec, ml_tmp_11_tm_min, ml_tmp_11_tm_hour, ml_tmp_11_tm_mday, ml_tmp_11_tm_mon, ml_tmp_11_tm_year, ml_tmp_11_tm_wday, ml_tmp_11_tm_yday, ml_tmp_11_tm_isdst};
    ML_Tuple<9> r = ML_Tuple<9>(ctx, vs);
    ml_arg_date = r;
  };
  return ml_arg_date;
}

ML_Value ml_stub_mkTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_date;
  ML_Value ml_arg_time;
  Date_t *ml_op_date;
  Time_t *ml_op_time;
  Time_t out_ml_op_time;
  Date_t ml_tmp_12;
  ML_Value ml_tmp_13_seconds;
  ML_Value ml_tmp_13_uSeconds;
  ml_op_time = &out_ml_op_time;
  ml_arg_date = v;
  (ml_tmp_12).tm_sec = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 1)))).Val();
  (ml_tmp_12).tm_min = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 2)))).Val();
  (ml_tmp_12).tm_hour = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 3)))).Val();
  (ml_tmp_12).tm_mday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 4)))).Val();
  (ml_tmp_12).tm_mon = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 5)))).Val();
  (ml_tmp_12).tm_year = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 6)))).Val();
  (ml_tmp_12).tm_wday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 7)))).Val();
  (ml_tmp_12).tm_yday = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 8)))).Val();
  (ml_tmp_12).tm_isdst = (*(reinterpret_cast<(ML_Int) *> (&((*(reinterpret_cast<(ML_Tuple<9>) *> (&(ml_arg_date))).Get(ctx, 9)))).Val();
  ml_op_date = &ml_tmp_12;
  mkTime (ml_op_date, ml_op_time);
  ml_tmp_13_secondsML_Int32(ctx,(*(ml_op_time)).seconds);
ml_tmp_13_uSecondsML_Int32(ctx,(*(ml_op_time)).uSeconds);
  {
    ML_Value vs[] = {ml_tmp_13_seconds, ml_tmp_13_uSeconds};
    ML_Tuple<2> r = ML_Tuple<2>(ctx, vs);
    ml_arg_time = r;
  };
  return ml_arg_time;
}

ML_Value ml_stub_getCPUTime (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_u;
  ML_Value ml_arg_s;
  ML_Value ml_arg_g;
  Time_t *ml_op_u;
  Time_t *ml_op_s;
  Time_t *ml_op_g;
  Time_t out_ml_op_u;
  Time_t out_ml_op_s;
  Time_t out_ml_op_g;
  ML_Value ml_tmp_14_seconds;
  ML_Value ml_tmp_14_uSeconds;
  ML_Value ml_tmp_15_seconds;
  ML_Value ml_tmp_15_uSeconds;
  ML_Value ml_tmp_16_seconds;
  ML_Value ml_tmp_16_uSeconds;
  ml_op_u = &out_ml_op_u;
  ml_op_s = &out_ml_op_s;
  ml_op_g = &out_ml_op_g;
  getCPUTime (ctx,ml_op_u, ml_op_s, ml_op_g);
  ml_tmp_14_secondsML_Int32(ctx,(*(ml_op_u)).seconds);
ml_tmp_14_uSecondsML_Int32(ctx,(*(ml_op_u)).uSeconds);
  {
    ML_Value vs[] = {ml_tmp_14_seconds, ml_tmp_14_uSeconds};
    ML_Tuple<2> r = ML_Tuple<2>(ctx, vs);
    ml_arg_u = r;
  };
  ml_tmp_15_secondsML_Int32(ctx,(*(ml_op_s)).seconds);
ml_tmp_15_uSecondsML_Int32(ctx,(*(ml_op_s)).uSeconds);
  {
    ML_Value vs[] = {ml_tmp_15_seconds, ml_tmp_15_uSeconds};
    ML_Tuple<2> r = ML_Tuple<2>(ctx, vs);
    ml_arg_s = r;
  };
  ml_tmp_16_secondsML_Int32(ctx,(*(ml_op_g)).seconds);
ml_tmp_16_uSecondsML_Int32(ctx,(*(ml_op_g)).uSeconds);
  {
    ML_Value vs[] = {ml_tmp_16_seconds, ml_tmp_16_uSeconds};
    ML_Tuple<2> r = ML_Tuple<2>(ctx, vs);
    ml_arg_g = r;
  };
  {
    ML_Value vs[] = {ml_arg_u, ml_arg_s, ml_arg_g};
    ML_Tuple<3> r = ML_Tuple<3>(ctx, vs);
      return r;
  };
}

ML_Value ml_stub_cmdName (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_s;
  char **ml_op_s;
  char *out_ml_op_s;
  ml_op_s = &out_ml_op_s;
  cmdName (ml_op_s);
  ml_arg_s = ML_String(ctx, *(ml_op_s));
  return ml_arg_s;
}

ML_Value ml_stub_cmdArgs (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_string_list_t ml_opresult;
  ml_opresult = cmdArgs (ctx);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

