
/*
 * This file was automatically generated by ml-idl
 * (Mon Aug 13 14:55:08 2007)
 */

#include "ml-base.h"
#include "ml-values.h"
#include "ml-objects.h"

#include "smlnj-runtime.h"

ML_Value ml_stub_allocCode (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_nbytes;
  ML_word8arr_t ml_opresult;
  int ml_op_nbytes;
  ml_arg_nbytes = v;
  ml_op_nbytes = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_nbytes))).Val();
  ml_opresult = allocCode (ctx,ml_op_nbytes);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_mkExec (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_code;
  ML_Value ml_arg_entrypoint;
  ML_object_object_fn_t ml_opresult;
  ML_word8arr_t ml_op_code;
  int ml_op_entrypoint;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_code = ml_arg_tuple.Get(ctx, 1);
  ml_arg_entrypoint = ml_arg_tuple.Get(ctx, 2);
  ml_op_code = ml_arg_code;
  ml_op_entrypoint = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_entrypoint))).Val();
  ml_opresult = mkExec (ctx,ml_op_code, ml_op_entrypoint);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_mkLiterals (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_arg;
  ML_objectvec_t ml_opresult;
  ML_word8vec_t ml_op_arg;
  ml_arg_arg = v;
  ml_op_arg = ml_arg_arg;
  ml_opresult = mkLiterals (ctx,ml_op_arg);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_setTimer (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_sts;
  ML_bool_t ml_op_sts;
  ml_arg_sts = v;
  ml_op_sts = ml_arg_sts;
  setTimer (ctx,ml_op_sts);
  return ML_UNIT;
}

ML_Value ml_stub_getQuantum (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  int ml_opresult;
  ml_opresult = getQuantum ();
  ml_argresult = ML_Int(ml_opresult);
  return ml_argresult;
}

ML_Value ml_stub_setTimeArray (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_prof_cnt_array;
  ML_int_arr_opt_t ml_op_prof_cnt_array;
  ml_arg_prof_cnt_array = v;
  ml_op_prof_cnt_array = ml_arg_prof_cnt_array;
  setTimeArray (ctx,ml_op_prof_cnt_array);
  return ML_UNIT;
}

ML_Value ml_stub_intervalTick (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_a;
  ML_Value ml_arg_b;
  ML_int32_t *ml_op_a;
  int *ml_op_b;
  ML_int32_t out_ml_op_a;
  int out_ml_op_b;
  ml_op_a = &out_ml_op_a;
  ml_op_b = &out_ml_op_b;
  intervalTick (ctx,ml_op_a, ml_op_b);
  ml_arg_a = *(ml_op_a);
  ml_arg_b = ML_Int(*(ml_op_b));
  {
    ML_Value vs[] = {ml_arg_a, ml_arg_b};
    ML_Tuple<2> r = ML_Tuple<2>(ctx, vs);
      return r;
  };
}

ML_Value ml_stub_setIntTimer (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_itv;
  ML_int_pair_opt_t ml_op_itv;
  ml_arg_itv = v;
  ml_op_itv = ml_arg_itv;
  setIntTimer (ctx,ml_op_itv);
  return ML_UNIT;
}

ML_Value ml_stub_exportHeap (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_fname;
  ML_bool_t ml_opresult;
  char *ml_op_fname;
  ml_arg_fname = v;
  ml_op_fname = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_fname))).Val();
  ml_opresult = exportHeap (ctx,ml_op_fname);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_listSignals (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_sysconst_list_t ml_opresult;
  ml_opresult = listSignals (ctx);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_getSigState (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_sc;
  int ml_opresult;
  ML_sysconst_t ml_op_sc;
  ml_arg_sc = v;
  ml_op_sc = ml_arg_sc;
  ml_opresult = getSigState (ctx,ml_op_sc);
  ml_argresult = ML_Int(ml_opresult);
  return ml_argresult;
}

ML_Value ml_stub_setSigState (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_sc;
  ML_Value ml_arg_i;
  ML_sysconst_t ml_op_sc;
  int ml_op_i;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_sc = ml_arg_tuple.Get(ctx, 1);
  ml_arg_i = ml_arg_tuple.Get(ctx, 2);
  ml_op_sc = ml_arg_sc;
  ml_op_i = (*(reinterpret_cast<(ML_Int) *> (&(ml_arg_i))).Val();
  setSigState (ctx,ml_op_sc, ml_op_i);
  return ML_UNIT;
}

ML_Value ml_stub_getSigMask (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_sysconst_list_opt_t ml_opresult;
  ml_opresult = getSigMask (ctx);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_setSigMask (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_m;
  ML_sysconst_list_opt_t ml_op_m;
  ml_arg_m = v;
  ml_op_m = ml_arg_m;
  setSigMask (ctx,ml_op_m);
  return ML_UNIT;
}

ML_Value ml_stub_pauseUntilSig (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  pauseUntilSig (ctx);
  return ML_UNIT;
}

ML_Value ml_stub_rawArgv (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_string_list_t ml_opresult;
  ml_opresult = rawArgv (ctx);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_shiftArgv (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  shiftArgv ();
  return ML_UNIT;
}

ML_Value ml_stub_sysInfo (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_name;
  ML_string_opt_t ml_opresult;
  char *ml_op_name;
  ml_arg_name = v;
  ml_op_name = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_name))).Val();
  ml_opresult = sysInfo (ctx,ml_op_name);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_gcControl (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_cmds;
  ML_string_intref_list_t ml_op_cmds;
  ml_arg_cmds = v;
  ml_op_cmds = ml_arg_cmds;
  gcControl (ctx,ml_op_cmds);
  return ML_UNIT;
}

ML_Value ml_stub_debug (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_s;
  char *ml_op_s;
  ml_arg_s = v;
  ml_op_s = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_s))).Val();
  debug (ctx,ml_op_s);
  return ML_UNIT;
}

ML_Value ml_stub_dummy (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_s;
  char *ml_op_s;
  ml_arg_s = v;
  ml_op_s = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_s))).Val();
  dummy (ml_op_s);
  return ML_UNIT;
}

ML_Value ml_stub_recordConcat (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_rec1;
  ML_Value ml_arg_rec2;
  ML_object_t ml_opresult;
  ML_object_t ml_op_rec1;
  ML_object_t ml_op_rec2;
  ML_Tuple<2>ml_arg_tuple = (*(reinterpret_cast<(ML_Tuple<2>) *> (&(v)));
  ml_arg_rec1 = ml_arg_tuple.Get(ctx, 1);
  ml_arg_rec2 = ml_arg_tuple.Get(ctx, 2);
  ml_op_rec1 = ml_arg_rec1;
  ml_op_rec2 = ml_arg_rec2;
  ml_opresult = recordConcat (ctx,ml_op_rec1, ml_op_rec2);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_record1 (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_obj;
  ML_object_t ml_opresult;
  ML_object_t ml_op_obj;
  ml_arg_obj = v;
  ml_op_obj = ml_arg_obj;
  ml_opresult = record1 (ctx,ml_op_obj);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_blastIn (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_s;
  ML_object_t ml_opresult;
  char *ml_op_s;
  ml_arg_s = v;
  ml_op_s = (*(reinterpret_cast<(ML_String) *> (&(ml_arg_s))).Val();
  ml_opresult = blastIn (ctx,ml_op_s);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

ML_Value ml_stub_blastOut (ML_Context *ctx,ML_Value v) {
  ML_Value ml_result;
  ML_Value ml_argresult;
  ML_Value ml_arg_obj;
  ML_word8vec_t ml_opresult;
  ML_object_t ml_op_obj;
  ml_arg_obj = v;
  ml_op_obj = ml_arg_obj;
  ml_opresult = blastOut (ctx,ml_op_obj);
  ml_argresult = ml_opresult;
  return ml_argresult;
}

