
(**********************************************************************
 *
 *  This file was automatically generated by ml-fred
 *  (Fri May  4 11:10:31 2001)
 *
 **********************************************************************)

signature Idl_PARSER_SIG = sig
  val parse : TextIO.instream -> IdlParseTree.start
end
