
/*
 * This file was automatically generated by ml-idl
 * (Mon Aug 13 14:55:08 2007)
 */

ML_CFunction fnTbl[] = {
  ML_CFunction(ml_stub_allocCode, "allocCode")
  ML_CFunction(ml_stub_mkExec, "mkExec")
  ML_CFunction(ml_stub_mkLiterals, "mkLiterals")
  ML_CFunction(ml_stub_setTimer, "setTimer")
  ML_CFunction(ml_stub_getQuantum, "getQuantum")
  ML_CFunction(ml_stub_setTimeArray, "setTimeArray")
  ML_CFunction(ml_stub_intervalTick, "intervalTick")
  ML_CFunction(ml_stub_setIntTimer, "setIntTimer")
  ML_CFunction(ml_stub_exportHeap, "exportHeap")
  ML_CFunction(ml_stub_listSignals, "listSignals")
  ML_CFunction(ml_stub_getSigState, "getSigState")
  ML_CFunction(ml_stub_setSigState, "setSigState")
  ML_CFunction(ml_stub_getSigMask, "getSigMask")
  ML_CFunction(ml_stub_setSigMask, "setSigMask")
  ML_CFunction(ml_stub_pauseUntilSig, "pauseUntilSig")
  ML_CFunction(ml_stub_rawArgv, "rawArgv")
  ML_CFunction(ml_stub_shiftArgv, "shiftArgv")
  ML_CFunction(ml_stub_sysInfo, "sysInfo")
  ML_CFunction(ml_stub_gcControl, "gcControl")
  ML_CFunction(ml_stub_debug, "debug")
  ML_CFunction(ml_stub_dummy, "dummy")
  ML_CFunction(ml_stub_recordConcat, "recordConcat")
  ML_CFunction(ml_stub_record1, "record1")
  ML_CFunction(ml_stub_blastIn, "blastIn")
  ML_CFunction(ml_stub_blastOut, "blastOut")
}
