
(**********************************************************************
 *
 *  This file was automatically generated by ml-fred
 *  (Fri May  4 11:10:31 2001)
 *
 **********************************************************************)

structure IdlExn : Idl_EXN_SIG = struct
exception Parser of string
exception Lexer of string
end
